baseURL = "https://www.geteduroam.app"
locale = "en-GB"
title = "geteduroam"
theme = "letswifi"
enableGitInfo = true

sectionPagesMenu = 'main'

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 1

[params]
