baseURL = "https://www.geteduroam.app"
locale = "en-GB"
title = "geteduroam"
theme = "letswifi"
enableGitInfo = true

[menus]
  [[menus.main]]
    name = 'Project'
    pageRef = '/project/information/introduction/'
    weight = 10
  [[menus.main]]
    name = 'Providers'
    pageRef = '/provider/idp/cat/cat/'
    weight = 20
  [[menus.main]]
    name = 'Technical'
    pageRef = '/tech/info/contribute/'
    weight = 30

[markup.goldmark.renderer]
# Allow HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 1

[params]
